server:
  servlet:
    context-path: /api/v1
    session:
      timeout: 10m
      cookie:
        http-only: true
        same-site: lax

spring:
  application:
    name: corebank
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 50
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: false