spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minicore_scratch?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=UTC&forceConnectionTimeZoneToSession=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:localpw}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: build/generated-schema.sql
              create-source: metadata
  flyway:
    enabled: false
